### ISSUE TITLE
Debug fields not available

### ISSUE THREAD

**Issue by giacomo892** [iNavFlight/blackbox-log-viewer#11]
I wasn't able to debug raw gyro. Here the log I used from 1.8 OMNIBUS F3

[LOG00004.TXT](https://github.com/iNavFlight/blackbox-log-viewer/files/1581960/LOG00004.TXT)

**Comment by DzikuVx** [comment]
Fixed in 4e0cd01c32c5e8c0e0e2ad545b36fc00ff6f8c48
