### ISSUE TITLE
Show navPos[2] value

### ISSUE THREAD

**Issue by giacomo892** [iNavFlight/blackbox-log-viewer#14]
Could be neat is we can display the navPos[2] value in meters inside the brackets so it can be directly compared with baro.

![image](https://user-images.githubusercontent.com/20860004/36646069-c47ac4bc-1a72-11e8-8da4-054c7f41d2c7.png)

**Comment by DzikuVx** [comment]
Done

**Comment by giacomo892** [comment]
Thanks!
