### ISSUE TITLE
Incorrect frequencies on analyser graph

### ISSUE THREAD

**Issue by krzysztofmatula** [iNavFlight/blackbox-log-viewer#17]
When gyro task runs at different frequency than pid task, the frequencies on the analyser graph are shown incorrectly.

The following log was captured with 8k gyro loop and 4k pid loop. The oscillation period on gyro is ~7ms (~150Hz). The analyser shows peak at 4x lower freq (~38Hz):

[LOG00008-gyro8k-pid4k.TXT](https://github.com/iNavFlight/blackbox-log-viewer/files/1936043/LOG00008-gyro8k-pid4k.TXT)

When using 8k gyro loop and 2k pid loop the peek was shown at 2x lower freq (~77Hz).

**Comment by DzikuVx** [comment]
fixed in 0b6bc0a2b8c82ec9d78d966677ca282f8fbdacf3
