### ISSUE TITLE
INAV blackbox-log-viewer runs but will not open log files

### ISSUE THREAD

**Issue by steviegeek** [iNavFlight/blackbox-log-viewer#25]
INAV blackbox-log-viewer downloaded today 28 Dec 2018 starts in Chrome browser, allows me to select a log file to open but does not open it, does nothing !, no error messages etc..
Log files tried are 2,857KB and 10,096KB recorded yesterday on SDcard using MATEK F722 STD running v2.0.1
CHROME says I'm running latest version, Version 71.0.3578.98 (Official Build) (64-bit), on Win7 PRO on Intel i5
Assistance most welcome :-)
Thanks Steve

![image](https://user-images.githubusercontent.com/38876209/50510136-736b1500-0a80-11e9-851c-207729d49bca.png)

**Comment by steviegeek** [comment]
BTW, these log files open OK in Cleanflight and Betaflight Blackbox Explorers
Sreve

**Comment by steviegeek** [comment]
Was using old file, found latest, all OK

**Comment by i3130002** [comment]
May I ask for some of your sample log files ? I want to convert my logs into INVA ones so I need some working logs. Thanks
