### ISSUE TITLE
"Error opening log: No logs in this file could be parsed successfully"

### ISSUE THREAD

**Issue by Seeelefant** [iNavFlight/blackbox-log-viewer#36]
The message "Error opening log: No logs in this file could be parsed successfully" shows up when I try to open LOG files created with INAV 2.2., all the older LOG files can still be opened and examined without problems. 
[LOG00103.TXT](https://github.com/iNavFlight/blackbox-log-viewer/files/3336681/LOG00103.TXT)
INAV Blackbox Explorer! Version 3.2

**Comment by DzikuVx** [comment]
Fixed, new version will be released soon
