### ISSUE TITLE
"Error opening log"

### ISSUE THREAD

**Issue by VitDetz** [iNavFlight/blackbox-log-viewer#40]
Blackbox problem: "Error opening log: No logs in this file could be parsed successfully"
INAV Blackbox Explorer version v3.3.0 
FC - Matek F405ctr
Changing the recording speed modes: 100/88/80/75/67/50 /% ... etc., as well as replacing the SD card and reformatting it, did not solve the problem.
Replacing the flight controller with a similar one did not solve the problem.
Plasmatree / PID-Analyzer - crash when trying to open a log file.
Your cakes are inedible gentlemen! It's time to start cooking normal food)))
[LOG00001.TXT](https://github.com/iNavFlight/blackbox-log-viewer/files/3787332/LOG00001.TXT)

**Comment by AlexAlle2020** [comment]
and also OMNIBUS F4 NANO V6 / Error opening log: No logs in this file could be parsed successfully

**Comment by DzikuVx** [comment]
Log is damaged
