### ISSUE TITLE
Missing field encoding header for field #0 'GPS_fixType'

### ISSUE THREAD

**Issue by jacoues** [iNavFlight/blackbox-log-viewer#42]
Got confused and originally posted to the cleanflight repo even though I am using the INAV blackbox log viewer.. so I'm reposting to the appropriate repo.

Hi all, I am running a Lumenier F7 dual gyro f7 controller with the Matek F422SE firmware on INAV. I recorded a flight using the blackbox logger with a Beitian 880 GPS and compass module and tried to view the log. The explorer is unable to parse the data and returns the following error:
Missing field encoding header for field #0 'GPS_fixType'

WIth Blackbox decode tools I was able to get three files out, but they are very short and do not contain the logs.

**Comment by jacoues** [comment]
My previous log must have been corrupted because I flew again today with the same configuration and the viewer works again..

**Comment by avselang** [comment]
My explorer is unable to parse the data and returns the following error : Missing field encoding header for field #0 'activeWpNumber'
