### ISSUE TITLE
Altitude should be on the same Y scale (i.e. navPos[2](m) and baro (m))

### ISSUE THREAD

**Issue by mf0o** [iNavFlight/blackbox-log-viewer#43]
**current state:**
Debugging altitude issues is quite hard as the navPos[2] seems to be on a different Y-scale as the baro(m).

Here for example the readings are almost identical, but the lines are not close to eachother
![Bildschirmfoto 2020-06-17 um 14 08 08](https://user-images.githubusercontent.com/51818950/84896295-fed8cb80-b0a3-11ea-905d-8e2ca9c5e5e2.png)

A few seconds later, barometer reads 56m, so I would expect the green line higher than the red navPos[2].
![Bildschirmfoto 2020-06-17 um 13 58 56](https://user-images.githubusercontent.com/51818950/84896120-a86b8d00-b0a3-11ea-9375-2190d8cbc5eb.png)

---
**expected behaviour:**

It should more look like this (data exported and graphed), the red bar marks the same second/altitude as in the BBE above:
![Bildschirmfoto 2020-06-17 um 13 59 10](https://user-images.githubusercontent.com/51818950/84896491-56773700-b0a4-11ea-963d-82a7fac7c83c.png)

---
**version:**
- iNav 2.4
- BBE 3.4.0

**Comment by spatzengr** [comment]
fixed in #87

**Comment by spatzengr** [comment]
@pawel-spychalski, you should be able to close this issue too.  :-)
