### ISSUE TITLE
Analyser shows "InfinityHz" for all frequency labels

### ISSUE THREAD

**Issue by IVData** [iNavFlight/blackbox-log-viewer#45]
Using the attached file I cannot see any frequencies in the analyser display, it just says "InfinityHz".

Tested on windows and linux versions of latest blackbox log viewer, inav 2.5 (maybe 2.5.1?) on a F405-CTR
[LOG00003.TXT](https://github.com/iNavFlight/blackbox-log-viewer/files/5127256/LOG00003.TXT)

**Comment by DzikuVx** [comment]
It's fixed in INAV 3
