### ISSUE TITLE
navPos[0], navPos[1], tgtNavPos[0], tgtNavPos[1] always 0

### ISSUE THREAD

**Issue by alccrl** [iNavFlight/blackbox-log-viewer#53]
Looking at logs, gps latitude and longitude are not shown, cannot find any value representing horizontal position.
Many flights analyzed, always same behaviour.

Setup:
FC mateksys F722-STD + magnetometer and gps
InavFlight 2.6.1
Inav log viewer 3.4 (bot Linux and Win32)

Any idea ?

Alfredo

**Comment by DzikuVx** [comment]
As checked today, position and other data was correctly shown. This seems to be caused by the recording part, not playing

**Comment by alccrl** [comment]
I did not investigate further, but I realized that position is better decoded by blackbox_decode tool, because LAT and LONG do not make much sense in a graph y(x) representation.
