### ISSUE TITLE
Heading (yaw) is shown sometime randomic

### ISSUE THREAD

**Issue by alccrl** [iNavFlight/blackbox-log-viewer#54]
Looking at logs, heading (yaw) values are randomic for some flight.
When ok, yaw heading shows a 70 (about) degrees offest added value to the range 0-360.    
Many flights analyzed, always same behaviour.

Note (may help) : inav Mag configuration is not 0, it is cw 270 flip.
Setup:
FC mateksys F722-STD + magnetometer and gps
InavFlight 2.6.1
Inav log viewer 3.4 (bot Linux and Win32)

Any idea ?

Alfredo

**Comment by DzikuVx** [comment]
`heading` is artificially computed field by the explorer itself and as such does not reflect actual heading.
Heading should be obtained from `attitude[2]` field which is heading from the flight controller
