### ISSUE TITLE
Inflight adjustments shown wrong in blackbox explorer

### ISSUE THREAD

**Issue by DeepnineRC** [iNavFlight/blackbox-log-viewer#59]
Hi,

Blackbox done with Inav 3.0.1 shows the wrong inflight adjustment. The value is right but the name of the setting is wrong. See attached image.

I was tuning pitch P, roll P, roll D, pitch D and got: Yaw I, Pitch I, rate profile, roll rate

![image](https://user-images.githubusercontent.com/16404343/126105979-2efceacb-0254-4dc4-94b1-e4192ef02e5f.png)

**Comment by DzikuVx** [comment]
Fixed in #69
