### ISSUE TITLE
rcCommand mapped to dps

### ISSUE THREAD

**Issue by DzikuVx** [iNavFlight/blackbox-log-viewer#6]
rcCommand is mapped to dps, while should stay unitless. This creates confusion. Either map rcCommand to dps or remove unit

**Comment by digitalentity** [comment]
Probably it's better to have rcCommand unitless since it's flight mode dependent and add units [dps] to axisRate

**Comment by DzikuVx** [comment]
Yes, but PID_error works in dps not too, so this might be deeped than that

**Comment by DzikuVx** [comment]
Either way, I will dig in in one day

**Comment by DzikuVx** [comment]
current implementation maps rcCommand to dsp and it will stay like this
