### ISSUE TITLE
Can’t launch the app on macOS BigSur

### ISSUE THREAD

**Issue by roroid** [iNavFlight/blackbox-log-viewer#70]
I was trying to launch the latest release of the app on macOS BigSur. Unfortunately, the app is not opening. I can see the app menu in the top bar but when trying to open a file app closes. I was opening the app considering that it was not signed.

**Comment by z2cooleo** [comment]
On macOS Monterey has the same issue.

**Comment by vinc13008** [comment]
+1 Same on Monterey

**Comment by roroid** [comment]
I have to build my executable from the source code, which somehow works. If someone else needs it, I can post the link.

**Comment by Sjullep** [comment]
+1 Same on Monterey

**Comment by febbyeka** [comment]
+1 same on my Monterey

**Comment by Pairan** [comment]
> I have to build my executable from the source code, which somehow works. If someone else needs it, I can post the link.

that would be nice - thanks!

**Comment by erstec** [comment]
Let's make build different way
Please try
https://www.icloud.com/iclouddrive/08cA-CcEEwR-rq-dQGPhlEPMQ#INAV-BlackboxExplorer%5FmacOS%5F4.0.0

**Comment by erstec** [comment]
NW updated to 0.6.1, if someone can test it - it would be nice.
https://www.icloud.com/iclouddrive/0c5_lzYpYso0S2pH8VEqxH8xQ#INAV-BlackboxExplorer_macOS_4.0.0_2

**Comment by martinmichaelfuchs** [comment]
Same problem here. I installed the INAV Blackbox Explorer 4.0 on macOS Big Sur version 11.6 but the Blackbox Explorer does not open. I know that the app isn't signed and I allowed my Mac to run it anyways, so that's not the issue. I see the app name in the top bar but can't get anywhere else

**Comment by Pairan** [comment]
Download it and it WORKS AS EXPECTED @erstec  Thank you so much for letting uns dig into our logs again!

**Comment by Bryksin** [comment]
The same, previous version does work, latest 4.0 does not open! UI not appearing
