### ISSUE TITLE
Frequency axis on Analyzer view shows infinite frequency

### ISSUE THREAD

**Issue by aviphysics** [iNavFlight/blackbox-log-viewer#91]
The frequency axis in the analyzer view shows infinite frequency. I am using the latest release version of iNav7 and the Blackbox log viewer available at the time of posting. The data from iNav appears valid and I can do the FFT and plot in Octave, so this seems to be a problem with the blackbox log viewer.

![image](https://github.com/iNavFlight/blackbox-log-viewer/assets/13427568/7645ee1e-21b1-4a4f-bcfb-88fd94bb1e09)

**Comment by Phil-MC** [comment]
I've seen a couple of comments on the forums with users asking what the frequencies are. The axis label seems to have taken over from the scale labels in the display.

**Comment by aviphysics** [comment]
> I've seen a couple of comments on the forums with users asking what the frequencies are. The axis label seems to have taken over from the scale labels in the display. I can't find the word infinite in the code. @DzikuVx

Did you try looking for "infinity"?

**Comment by Phil-MC** [comment]
I did look for infinity as well using github search and there were no hits in the code. I hope @DzikuVx has a look at this problem. I can see lots of users having problems with it. The graphs look OK, it's just the labelling.

**Comment by rts18** [comment]
@spatzengr If you find some time. Can you please take a look at this issue. Possibly caused by #86

**Comment by spatzengr** [comment]
@rts18 , yes.  I noticed the same issue but didn't associate it with #86 , but I can investigate to see wsup.

**Comment by balbusky21** [comment]
I'm having the same issue. Is there a fix yet for this? I'm having issues tunning my filters. or is there a work around?

**Comment by aviphysics** [comment]
> I'm having the same issue. Is there a fix yet for this? I'm having issues tunning my filters. or is there a work around?

My current work around is to use the last version of BBV

**Comment by Phil-MC** [comment]
I gather it can be caused by missing entries in the BB Recording. Try reducing the amount of data collected. Some of the FC's are at the limit of what their design can handle.

**Comment by aviphysics** [comment]
> I gather it can be caused by missing entries in the BB Recording. Try reducing the amount of data collected. Some of the FC's are at the limit of what their design can handle.

I don't think that is the problem here (or not the entire problem)

For one thing, BBV5 can render the FFT with scale without a problem from the same dataset that doesn't work in BBV7.

Have you been able to demonstrate a working FFT scale in BBV7?

**Comment by Phil-MC** [comment]
You need to verify that the log has no missing entries. There is an excellent set of BlackBox Tools written by Jonathan Hudson on Github, which can verify this. He can be contacted on our Discord Forum as @stronnag .

**Comment by aviphysics** [comment]
> You need to verify that the log has no missing entries. There is an excellent set of BlackBox Tools written by Jonathan Hudson on Github, which can verify this. He can be contacted on our Discord Forum as @stronnag .

Can you demonstrate that it works with any logs? Why does the BBV5 work with the logs?

**Comment by Phil-MC** [comment]
I think BBv5 is probably less fussy and skips over problems. BBv7 might be doing something new. Ask @stronnag on Discord. Sent from my Galaxy

**Comment by aviphysics** [comment]
> I think BBv5 is probably less fussy and skips over problems. BBv7 might be doing something new. Ask @stronnag on Discord. Sent from my Galaxy

Do you have any to examples of a successful frequency plot?

**Comment by Phil-MC** [comment]
![BB1](https://github.com/iNavFlight/blackbox-log-viewer/assets/65187658/fbc70776-9f99-4725-b45f-6e30f534fdc8)
![BB2](https://github.com/iNavFlight/blackbox-log-viewer/assets/65187658/ababa7bb-e421-465d-b98f-5f96e126307c)

These were produced more than a year ago and show vibration before and after replacing a problem motor.

Unfortunately I did not record the version of BB explorer I used but it was 2023/24. But it wasn't the current one!

**Comment by Phil-MC** [comment]
What FC generated the BB recording?

**Comment by rts18** [comment]
> I don't think that is the problem here (or not the entire problem)
For one thing, BBV5 can render the FFT with scale without a problem from the same dataset that doesn't work in BBV7.

@aviphysics I can confirm your findings. I see infinity on every copter or plane log I record, when viewed with blackbox explorer 7. 
However all logs render the FFT scale consistently with BBE 5.

**Comment by mmosca** [comment]
7.0.1 should fix this.

**Comment by Phil-MC** [comment]
Presumably, you refer to the firmware and not the CONFIGURATOR. Does this extend up the line to 7.1.1 and the latest 7.1.2 ?

**Comment by mmosca** [comment]
7.0.1 of blackbox log viewer.

**Comment by Phil-MC** [comment]
Thanks, I should have thought of that....
